# Generated by Django 5.0.1 on 2025-06-17 15:14

import django.db.models.deletion
import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="quote_number",
            field=models.CharField(
                default=quotes.models.generate_quote_number,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="quotes.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quote",
            name="options",
            field=models.ManyToManyField(blank=True, to="quotes.option"),
        ),
    ]
